# -*- coding: utf-8 -*-
"""
为已删除的文章生成 Cloudflare Pages 301 重定向规则（static/_redirects），
把旧 URL 的权重导向保留篇，避免 404。
"""
import os, re, io, json, subprocess, collections

ROOT = os.path.dirname(os.path.abspath(__file__))
POSTS = os.path.join(ROOT, 'content', 'posts')
REMOVED_LOG = os.path.join(ROOT, 'removed_posts.txt')
REDIRECTS = os.path.join(ROOT, 'static', '_redirects')


def git(*a):
    r = subprocess.run(list(a), cwd=ROOT, capture_output=True, text=True,
                       encoding='utf-8', errors='ignore')
    return r.stdout


def read_front(content=None, path=None):
    s = content if content is not None else io.open(path, encoding='utf-8').read()
    m = re.match(r'---\n(.*?)\n---\n', s, re.S)
    head = m.group(1) if m else ''

    def get(k):
        mm = re.search(k + r':\s*"([^"]*)"', head)
        if mm:
            return mm.group(1)
        mm = re.search(k + r':\s*([^\s"\n]+)', head)
        return mm.group(1) if mm else ''

    return get('title'), get('slug')


meta = json.load(io.open(REMOVED_LOG, encoding='utf-8'))

# 当前保留文章的 slug
keep = {}
for f in sorted(x for x in os.listdir(POSTS) if x.endswith('.md')):
    _, slug = read_front(path=os.path.join(POSTS, f))
    keep[re.sub(r'^\d{4}-\d{2}-\d{2}-', '', f[:-3])] = slug

lines = ['# Cloudflare Pages redirects (auto-generated by dedup — DO NOT EDIT MANUALLY)',
         '# 已合并/删除的近重复文章 -> 保留篇（301 永久重定向，保留 SEO 权重）',
         '']
n = 0
skipped = []
for m in sorted(meta, key=lambda x: x['slug']):
    key = re.sub(r'^\d{4}-\d{2}-\d{2}-', '', m['file'][:-3])
    new = keep.get(key)
    if not new:
        skipped.append((m['slug'], '无同主题保留篇'))
        continue
    if new == m['slug']:
        # URL 本来就相同（同 slug 冲突组），保留篇已占据该 URL，无需重定向
        skipped.append((m['slug'], '与保留篇同 slug，无需重定向'))
        continue
    lines.append('/posts/%s/ /posts/%s/ 301' % (m['slug'], new))
    lines.append('/posts/%s /posts/%s/ 301' % (m['slug'], new))
    n += 1

# 保留原有手动规则以外的注释
io.open(REDIRECTS, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('生成 301 重定向: %d 个旧 URL（成对写入带/不带斜杠）' % n)
print('跳过: %d' % len(skipped))
for s, why in skipped[:6]:
    print('   %s  (%s)' % (s, why))
print('\n写入: %s' % REDIRECTS)
print('\n'.join(lines[:6]))
